version: '3.7'
services:
    postgres:
        image: postgres:15.2
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - '5432:5432'
        volumes: 
          - ./.pg-data:/var/lib/postgresql/data
