-- CreateTable
CREATE TABLE "Game" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "answer" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "Session" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "gameId" INTEGER NOT NULL,
    "owner" TEXT NOT NULL,
    "board" TEXT NOT NULL DEFAULT '????????????????????????????????????',
    "colors" TEXT NOT NULL DEFAULT 'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    "complete" BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT "Session_gameId_fkey" FOREIGN KEY ("gameId") REFERENCES "Game" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
